repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--experimental-string-processing"]
        language_version: python3.9

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--max-line-length", "90", "--extend-ignore", "E203, E501"]

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
      - id: pylint
        args:
          [
            "--output-format",
            "colorized",
            "--disable",
            "E0401, C0301, E0602, C0114",
            "--good-names-rgx",
            "df, [a-z]",
          ]
