[package]
name = "carpe-diem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.22"
handlebars = "4.3.5"
serde = "1.0.147"
serde_derive = "1.0.147"
toml = "0.5.9"
